name = "cybersmrt-test"
compatibility_date = "2025-10-19"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "cybersmrt-users"
database_id = "fe041848-b5e6-44b9-8de4-a43d4ef4c370"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true