name: Update Sitemap

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.html'              # Any HTML file anywhere
      - '!**/_*.html'            # Except templates
      - '!**/404.html'           # Except 404 page
      - '!admin/**'              # Except admin folder
  workflow_dispatch:

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate sitemap
        run: |
          node .github/scripts/generate-sitemap.js

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Auto-update sitemap.xml"
          git push